### ISSUE TITLE
labels containing instruction names parse as instruction rather than labels

### ISSUE THREAD

**Issue by E1thanz** [mattbatwings/newcpu#8]
example:
.return parses as RET
.normal parses as NOR

fix please <3

**Comment by E1thanz** [comment]
ok discovered vertical_line also parses as an instruction my theory is that ert parses as RET
anyhow ill also make the problem here clearer, when making these labels in the program, it will detect it as a label and not count it when parsing and stuff, but when running it in the simulator it will make every line from that point on 1 number higher so it jumps to the wrong address, if needed i can give code specific examples.

**Comment by mattbatwings** [comment]
seems to be working for me. specific code examples would be nice

**Comment by E1thanz** [comment]
![image](https://github.com/user-attachments/assets/3a20a137-90e8-4d6d-9286-7c134aacf7e1)
here you can see a case of the issue
it parses the "nor" in ".norlabel" as an instruction, but also it doesnt? for some reason it expects there to only be 3 instructions in the program (JMP LDI HLT) but when ran, it runs fine, thing is, it doesnt get to the actual instructions, it "runs" the labels, i think this is either an issue here or an issue with the way the godot simulator shows this.
first picture is start of program
second picture is end of program
![image](https://github.com/user-attachments/assets/c4f78346-3cbd-4129-ad6c-00f928e2c2a6)

**Comment by mattbatwings** [comment]
1. this is bad assembly, to the point where id say its invalid. i dont know how the assembler/simulator handles multiple labels in a row or two labels with the same value but we might not have accounted for these cases
2. you likely have an outdated version of the simulator, grab the latest release if you havent already. heres what it looks like for me on windows 
![image](https://github.com/user-attachments/assets/df2b84cd-62a2-48fa-8d76-60e97b50f4b5)

**Comment by ProtoSebastian** [comment]
this is a bug purely from the simulator, which was already fixed by the time E1thanz found it.
Please close this issue
